/** Wikipedia page titles for player slug disambiguation (photos, stats). */
export const WIKIPEDIA_TITLE_OVERRIDES = {
  "dusan-tadic": "Dušan Tadić",
  "dusan-vlahovic": "Dušan Vlahović",
  "mauro-icardi": "Mauro Icardi",
  "sergio-busquets": "Sergio Busquets",
  "luis-suarez": "Luis Suárez",
  "kylian-mbappe": "Kylian Mbappé",
  "ousmane-dembele": "Ousmane Dembélé",
  "leroy-sane": "Leroy Sané",
  vitinha: "Vitinha (footballer, born 2000)",
  rodri: "Rodri (footballer, born 1996)",
  "vinicius-junior": "Vinícius Júnior",
  "lamine-yamal": "Lamine Yamal",
  "khvicha-kvaratskhelia": "Khvicha Kvaratskhelia",
  "takefusa-kubo": "Takefusa Kubo",
  "youssef-en-nesyri": "Youssef En-Nesyri",
  "moises-caicedo": "Moisés Caicedo",
  "martin-odegaard": "Martin Ødegaard",
  "joao-pedro": "João Pedro (footballer, born 2001)",
  "rafael-leao": "Rafael Leão",
  "matheus-cunha": "Matheus Cunha",
  "lois-openda": "Loïs Openda",
  "nicolas-jackson": "Nicolas Jackson (footballer, born 2001)",
  "heung-min-son": "Son Heung-min",
  "bruno-guimaraes": "Bruno Guimarães",
  "matteo-politano": "Matteo Politano",
  "aurelien-tchouameni": "Aurélien Tchouaméni",
  "desire-doue": "Désiré Doué",
  "ngolo-kante": "N'Golo Kanté",
  "jeremy-jacquet": "Jérémy Jacquet",
  "jose-sa": "José Sá",
  "goncalo-inacio": "Gonçalo Inácio",
  "francisco-trincao": "Francisco Trincão",
  "francisco-conceicao": "Francisco Conceição",
  "warren-zaire-emery": "Warren Zaïre-Emery",
  "maghnes-akliouche": "Maghnes Akliouche",
  "nico-orielly": "Nico O'Reilly",
  "joao-cancelo": "João Cancelo",
  "joao-felix": "João Félix",
  "ruben-dias": "Rúben Dias",
  "ruben-neves": "Rúben Neves",
  "nuno-mendes": "Nuno Mendes (footballer, born 2002)",
  "dayot-upamecano": "Dayot Upamecano",
  "jules-kounde": "Jules Koundé",
  "leny-yoro": "Leny Yoro",
  "ibrahima-konate": "Ibrahima Konaté",
  "bradley-barcola": "Bradley Barcola",
  "phil-foden": "Phil Foden",
  "jordan-pickford": "Jordan Pickford",
  "marc-guehi": "Marc Guéhi",
  "ivan-toney": "Ivan Toney",
  "elliot-anderson": "Elliot Anderson (footballer, born 2001)",
  "jarell-quansah": "Jarell Quansah",
  "diogo-costa": "Diogo Costa",
  "joao-neves": "João Neves",
  "lucas-hernandez": "Lucas Hernández",
  "theo-hernandez": "Theo Hernández",
  "rui-silva": "Rui Silva (footballer, born 1994)",
  "lucas-da-cunha": "Lucas Da Cunha",
  "samu-costa": "Samú Costa",
  "tino-livramento": "Tino Livramento",
  "esteban-lepaul": "Esteban Lepaul (footballer)",
};

export function wikiTitlesForPlayer(slug, name) {
  const primary = WIKIPEDIA_TITLE_OVERRIDES[slug] ?? name;
  const base = primary.replace(/\s+\([^)]+\)$/, "").trim();
  return [
    ...new Set([
      primary,
      base,
      `${base} (footballer)`,
      `${base} (football)`,
    ]),
  ];
}
